data_dir = "./data"
sample = 8

[[model]]
# Internal identifier for your own record. Used when storing and presenting the results.
name = "chatglm3-6b-sft-checkpoint100"
# Entries other than `name` are passed to `openai.OpenAI` or `openai.OpenAI.chat.completion.create`
base_url = "http://localhost:8000/v1"
api_key = "dummy-key"
max_retries = 1
model = "dummy-model-name"

[[model]]
name = "gpt-3.5"
api_key = "sk-..."
max_retries = 1
model = "gpt-3.5-turbo"


[[prompt]]
name = "demo-sleep-zh"
chat = """
user: 睡不着怎么办？
assistant: 你可以……
（略作沉思）
试试给我讲个故事呀。
user: 诶嘿，那你想听什么样的故事呢？
"""

[[prompt]]
name = "demo-sleep-en"
chat = """
user: What should I do if I can't fall asleep?
assistant: Hmmm, maybe...
*pondering*
you can try telling me a story.
user: lol, what kind of story do you like?
"""
