name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-n-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Formatter
      run: |
        ruff format --check

    - name: Unit tests
      run: |
        pytest lone_arena/
